### PR TITLE
fix: silently ignore empty proxy host values

### LINKED ISSUE #1098: Check for empty proxy hosts
### Describe the bug

We're seeing the following issue in our logs which I've tracked down to `EnvironmentProxySelector`

`Caused by: aws.smithy.kotlin.runtime.ClientException: Could not parse http.proxyHost="", http.proxyPort="0" into a valid proxy URL`

### Expected behavior

Ideally the `EnvironmentProxySelector` would check the length of the proxy host before attempting to use it, like `DefaultProxySelector` does [here](https://github.com/frohoff/jdk8u-jdk/blob/da0da73ab82ed714dc5be94acd2f0d00fbdfe2e9/src/share/classes/sun/net/spi/DefaultProxySelector.java#L225)

### Current behavior

If SQS detects an value for `proxy_host`, even if it's empty, it will attempt to use it and the connection will fail.

### Steps to Reproduce

I'm not entirely sure how this is being set in the wild, but we've been able to reproduce it by setting the property before initialising the SQS client

`System.setProperty("http.proxyHost", "")`

### Possible Solution

Check the length of the host value before using the proxy settings

### Context

_No response_

### Smithy-Kotlin version

1.25

### Platform (JVM/JS/Native)

JVM

### Operating system and version

Android 8/9/10

### PR DESCRIPTION
**Pull request by ianbotsf**
## Issue \#

Closes #1098 

## Description of changes

This changes adds handling for empty/blank proxy host values sourced from environment variables and system properties. The previous behavior was to throw an exception because blank strings couldn't be parsed into hosts.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: runtime/protocol/http-client/common/test/aws/smithy/kotlin/runtime/http/engine/EnvironmentProxySelectorTest.kt [hunk 1]
```diff
@@ -49,6 +49,10 @@ class EnvironmentProxySelectorTest {
     private val tests = listOf(
         // no props
```
Comment (lauzadis) [inline runtime/protocol/http-client/common/test/aws/smithy/kotlin/runtime/http/engine/EnvironmentProxySelectorTest.kt:50]: For completeness should we also test a blank string for the `http.nonProxyHosts` property and `NO_PROXY` environment variable?

**Review by lauzadis — APPROVED** [review]
